### PR TITLE
Jest testing for functions add and remove task

### PR DESCRIPTION
**Pull request by jicamargo**
# Jest testing for functions add and remove task

This pull request introduces test functions specifically designed to validate the accuracy and reliability of the list manipulation functionalities related to adding and deleting list items. The main objective is to guarantee the correctness and robustness of these operations.

The affected files include 'addtasktoarray.test.js' and 'removetaskfromarray.test.js', which have been thoroughly tested to ensure comprehensive coverage of the corresponding functionality.

By incorporating these tests, we aim to enhance the overall stability and quality of the codebase, facilitating smoother and error-free list manipulation for future development and usage.

This pull request represents a significant contribution towards maintaining the integrity of the application and promoting reliable list management within the project

---

Please review this pull request to ensure the correctness of the test implementations and their adherence to coding standards. Your feedback and suggestions are greatly appreciated.

### CODE REVIEW

**Review by V-Blaze — CHANGES_REQUESTED** [review]
## Hi @jicamargo, @mhnazary, @danielochuba , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

giphy


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights

- Tests are passing✔✔
- Descriptive pull request summary :heavy_check_mark: 

 ## Required Changes ♻️
- [x] You did a great job, :+1:  :+1:  All your tests are passing.. But as required by Microverse, all links on the readme must be working, Current your LICENSE link is currently broken, it leads to a 404 error page, I'll suggest you add an MIT license to your project and link it correctly. :smile: :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._Hi @jicamargo, @mhnazary @danielochuba

**Comment by jicamargo** [comment]
Thank you @V-Blaze, I add the LICENSE.

**Review by Kamba56 — APPROVED** [review]
Hi @jicamargo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] Great job using jest to test for add and delete functionalities!👏👏👏
- [x] Great job using mocks!👏👏👏
- [x]!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [x] Kinldy work equally with your team in the future. It is encouraged to work together with you coding partners and have similar number of commits in all pair-programming tasks.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jicamargo** [comment]
Thank you @Kamba56

**Pull request merged**
